# Base config for docker-compose and docker stack.
version: "3.4"
services:
  mongo:
    image: mongo:3.2
    volumes:
      - db:/data/db
      - configdb:/data/configdb
#  meteor:
#    depends_on:
#      - mongo
#    environment:
#      METEOR_ALLOW_SUPERUSER: 1
#      PORT: 3000
#      MONGO_URL: mongodb://mongo:27017
#      IMAGE_URL: /img/
volumes:
  db:
  configdb:
